#!/usr/bin/env bash

check_factor() {
    if [ $# -eq 2 ]; then
        num1=$1
        num2=$2
    else
        num1=$(echo "$1" | cut -d':' -f1)
        num2=$(echo "$1" | cut -d':' -f2)
    fi

    if [ "$num2" -gt "$num1" ]; then
        temp=$num1
        num1=$num2
        num2=$temp
    fi

    echo "$num1 * $num2"
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
else
    while read -r i; do
        result=$(factor "$i")
        check_factor "$result"
    done < "$1"
fi
